name: "Build ISO"

on:
  push:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - name: Free Disk Space
      uses: insightsengineering/disk-space-reclaimer@v1

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install nix
      uses: cachix/install-nix-action@v25
      with:
        nix_path: "nixpkgs=channel:nixos-unstable"
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Show nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'

    - name: Build the ISO
      env:
        NIXPKGS_ALLOW_UNFREE: 1
      run: |
        nix run nixpkgs#nixos-generators -- --flake .#minix --format-path genfmts/isoplus.nix -o minix.iso

    - name: Archive ISO
      uses: actions/upload-artifact@v4
      with:
        name: minix.iso
        path: minix.iso
