name: Grawler checks

on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: wget https://github.com/mrtnvgr/grawler/releases/latest/download/grawler
    - run: chmod +x grawler; ./grawler check
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
